version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - run: |
          gem install bundler
          bundle check || bundle install
          bundle exec rubocop
          bundle exec fasterer
          bundle exec rspec
workflows:
  version: 2
  test:
    jobs:
      - test
